---
title: "Positronのメモ"
subtitle: ""
description: ""
author: ""
date: "2024-07-25"
date-modified: "2024-08-28"
categories: [Positron]
---

## PositronでVimのキーバインディングを使う

VSCodeのExtensionであるvscodevimを導入する。
Macで使う場合はカーソル移動時などに連続でキーを入力することができなかったので設定をする必要がある。
ExtensionのDetailsのところにも書いてあるが、ターミナルで`defaults`コマンドを使って設定する。

```{.bash}
# これがDetailsのところに書いてあるコマンド。これを実行してもPositronでは反映されない。
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
```

Positronの設定のdomainを探す。

```{.bash}
defaults find positron | grep positron
#> Found 8 keys in domain 'com.rstudio.positron': {
#>                 "bundle-identifier" = "com.rstudio.positron";
```

元のコマンドのdomainを書き換えて実行し、Positronを再起動することで、設定が有効化される。

```{.bash}
defaults write com.rstudio.positron ApplePressAndHoldEnabled -bool false
```

## RStudioのキーマップを使う

Settingsから"rstudio"と検索して、「RStudio > Keymap: Enable」にチェックを入れる。

{{< kbd mac=Command win=Control linus=Control >}} + {{< kbd Shift >}} + {{< kbd M >}} で挿入するパイプ演算子は、Settingsで「Positron > R: Pipe」から選択する。

## 行の折り返し

行を折り返すかどうかは、{{< kbd Alt >}} + {{< kbd Z >}} で切り替えられる。
ソースペインでもターミナルでも使える。

## 空白文字の表示

{{< kbd mac=Command win=Ctrl linux=Ctrl >}} + {{< kbd , >}} を押してSettingsを開く。
検索窓に「whitespace」と入力し、Editor: Render Whitespaceをallにする。

## タブを入力

{{< kbd mac=Command win=Ctrl linux=Ctrl >}} + {{< kbd Shift >}} + {{< kbd P >}} を押して、コマンドパレットを開く。
「open keyboard」と入力し、Preferences: Open Keyboard Shortcuts (JSON)を選択する。
`keybindings.json`が開くので、以下を追記する。

```{.json filename="keybindings.json"}
[
  {
    "key": "ctrl+t",
    "command": "type",
    "args": { "text": "\t" },
    "when": "editorTextFocus"
  }
  // Other settings
]
```

そうするとエディターで {{< kbd Ctrl >}} + {{< kbd T >}} を押すとタブを入力することができる。

参考：[Visual Studio Code でタブを入力する](https://kotsukotsu.work/tech/2020-10-15-visual-studio-code-%E3%81%A7%E3%82%BF%E3%83%96%E3%82%92%E5%85%A5%E5%8A%9B%E3%81%99%E3%82%8B/)

## Ubuntu 20

PositronをUbuntu 20向けにビルドする際に、`glibc`の互換性の問題があるらしい。

[Positron does not run on Ubuntu 20 (glibc incompatibility) #3854](https://github.com/posit-dev/positron/issues/3854)

そのせいかはわからないが自分のUbuntu 20.04にインストールしたPositronもうまく動作しなかった。
（コンソールが起動しない。version 2024.08.0-48）
