project:
  type: website

website:
  title: "めも"
  navbar:
    left:
      - href: about.qmd 
        text: About
      - href: index.qmd
        text: Posts
      - text: Articles
        menu:
          - href: articles/R.qmd
            text: "R"
          - href: articles/Quarto.qmd
            text: "Quarto"
    right:
      - icon: github
        href: https://github.com/t-arae
  google-analytics: "G-543THBE9DB"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    lightbox: true

editor: source

