project:
  type: website

website:
  title: "めも"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/t-arae
  google-analytics: "G-543THBE9DB"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    lightbox: true

editor: source

