theme: "hugo-PaperMod"
baseURL: http://example.org/
languageCode: en-us
title: めも

menu:
  main:
    - name: categories
      url: /categories/
      weight: 10
    - name: tags
      url: /tags/
      weight: 10
    - name: home
      url: /
      weight: 10
    - name: archive
      url: /archives/
      weight: 10
    - name: search
      url: /search/
      weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    profileMode:
        enabled: true
        title: TA
        subtitle: 赤ベコかわいい
        imageUrl: "/beko.jpeg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: posts 
              url: /post/
            - name: archives
              url: /archives/
            - name: tags
              url: /tags/
